version: "3"

services:
  db:
    image: postgres:12-alpine
    environment:
      #PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/

  app:
    image: geoffjay/hatedit:0.1rc1
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    restart: unless-stopped

  ngrok:
    image: wernight/ngrok:latest
    depends_on:
      - app
    environment:
      NGROK_AUTH: ${NGROK_AUTHTOKEN}
      NGROK_REGION: ${NGROK_REGION}
      NGROK_HOSTNAME: ${NGROK_HOSTNAME}
      NGROK_PORT: ${NGROK_PORT}
    ports:
      - 4040:4040
    restart: unless-stopped

volumes:
  pgdata:
